#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri May 26 11:29:02 2023

@author: Daniel
"""

from numpy.random import randint
from time import sleep


while True:
    sleep(5)
    with open('shift.txt', 'w') as f:
        
        x = str(list(randint(50, 1200, 2)))
        print(x)
        f.write(x)
        f.close()
